routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('productList', 'ProductController@productList')->name('productList');
Route::post('addToCart', 'ProductController@addToCart')->name('addToCart');
Route::post('removeFromCart', 'ProductController@removeFromCart')->name('removeFromCart');
Route::get('cart', 'ProductController@cart')->name('cart');


Route::middleware('auth')->group(function () {
    Route::get('payment', 'PaymentController@payment')->name('payment');
    Route::post('purchase', 'PaymentController@purchase')->name('purchase');
});

Route::prefix('admin')->middleware('checkAdmin')->group(function () {
    Route::resource('products', 'ProductController', array('as'=>'admin'));
    Route::get('orderList', 'OrderController@index')->name('orderList');
    Route::post('approve', 'OrderController@approve')->name('approve');
});


Route::get('/home', 'HomeController@index')->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'description', 'price', 'status', 'category_id', 'brand_id'];

    public function orderItem()
    {
        return $this->belongsTo('App\Models\OrderItem', 'product_id');
    }

    public function category()
    {
        return $this->hasOne('App\Models\Category', 'category_id');
    }

    public function brand()
    {
        return $this->hasOne('App\Models\Brand', 'brand_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Repositories\Repository;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    protected $model;

    public function __construct(Product $product)
    {
        $this->model = new Repository($product);
    }

    public function productList()
    {
        return view('product/index')->with('products', $this->model->all());
    }

    public function index()
    {
        return view('product/admin/list')->with('products', $this->model->all());
    }

    public function store(Request $request)
    {
        $this->model->create($request->only($this->model->getModel()->fillable));
        return redirect()->route('admin.products.index')
            ->with('success','Product inserted successfully');
    }

    public function create()
    {
        $categories = Category::all();
        $brands = Brand::all();
        return view('product/admin/create')->with(['categories' => $categories, 'brands' =>$brands]);
    }

    public function edit(Product $product)
    {
        $categories = Category::all();
        $brands = Brand::all();

        return view('product/admin/show')->with(['product' => $this->model->show($product->id), 'categories' => $categories, 'brands' =>$brands]);
    }

    public function update(Request $request, Product $product)
    {
        $this->model->update($request->only($this->model->getModel()->fillable), $product->id);

        return redirect()->route('admin.products.index')
            ->with('success','Product updated successfully');
    }

    public function destroy(Product $product)
    {
        try {
            $this->model->delete($product->id);
        }catch (\Exception $ex) {
            return redirect()->route('admin.products.index')
                ->with('fail','Product could not be deleted');
        }

        return redirect()->route('admin.products.index')
            ->with('success','Product deleted successfully');
    }

    public function addToCart(Request $request)
    {
        $cookies = Cookie::get('products');
        if(!$cookies) {
            $cookies = [];
            $cookies[$request->id] = 1;
            Cookie::queue('products', serialize($cookies), 86400);
        }
        else {
            $parseCookies = unserialize($cookies);
            if (array_key_exists($request->id, $parseCookies)) {
                $parseCookies[$request->id] = $parseCookies[$request->id] + 1;
            }else {
                $parseCookies[$request->id] = 1;
            }

            Cookie::queue('products', serialize($parseCookies), 86400);
        }
    }

    public function removeFromCart(Request $request)
    {
        $cookies = Cookie::get('products');
        $parseCookies = unserialize($cookies);
        if (array_key_exists($request->id, $parseCookies)) {
            if($parseCookies[$request->id] != 1)
                $parseCookies[$request->id] = $parseCookies[$request->id] - 1;
            else
                unset($parseCookies[$request->id]);
        }

        Cookie::queue('products', serialize($parseCookies), 86400);

        $cookies = $parseCookies;
        $result = [];

        if($cookies) {
            $response = $this->model->getProductsWithArray(array_keys($cookies));
            $quantities = array_values($cookies);
            $result["response"] = $response;
            $result["quantities"] = $quantities;
        }

        return response()->json($result);
    }

    public function cart()
    {
        $cookies = Cookie::get('products');
        $response = [];
        $quantities = [];
        if($cookies) {
            $response = $this->model->getProductsWithArray(array_keys(unserialize($cookies)));
            $quantities = array_values(unserialize($cookies));
        }

        return view('product/cart')->with(['products' => $response, 'quantities' => $quantities]);
    }

}

resources/views/product/admin/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Product</div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="card-body">
                        <form action="{{ route('admin.products.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Enter name">
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea type="text" class="form-control" id="description" name="description"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="price">Price</label>
                                <input type="text" class="form-control" id="price" name="price" placeholder="Enter price">
                            </div>
                            <div class="form-group">
                                <label for="status">Status</label>
                                <select name="status" id="status" class="form-control">
                                    <option value="1">Active</option>
                                    <option value="0">Passive</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="category_id">Category</label>
                                <select name="category_id" id="category_id" class="form-control">
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="brand_id">Brand</label>
                                <select name="brand_id" id="brand_id" class="form-control">
                                    @foreach($brands as $brand)
                                        <option value="{{$brand->id}}">{{$brand->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/admin/list.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Products <span class="text-right"> <a class="btn btn-success" href="{{ route('admin.products.create') }}"> Create New Product</a></span>
                    </div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Description</th>
                                <th scope="col">Price</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody id="cartBody">
                            @foreach($products as $product)
                                    <tr>
                                        <th scope="row">{{$product->id}}</th>
                                        <td>{{$product->name}}</td>
                                        <td>{{$product->description}}</td>
                                        <td>${{$product->price}}</td>
                                        <td>
                                            <form action="{{ route('admin.products.destroy',$product->id) }}" method="POST">

                                                <a class="btn btn-info" href="{{ route('admin.products.edit',$product->id) }}">Edit</a>

                                                @csrf
                                                @method('DELETE')

                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/admin/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Product</div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="card-body">
                        <form action="{{ route('admin.products.update',$product->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ $product->name }}" placeholder="Enter name">
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea type="text" class="form-control" id="description" name="description">{{ $product->description }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="price">Price</label>
                                <input type="text" class="form-control" id="price" value="{{ $product->price }}" name="price" placeholder="Enter price">
                            </div>
                            <div class="form-group">
                                <label for="status">Status</label>
                                <select name="status" id="status" class="form-control">
                                    <option value="1" {{ ( $product->status == 1) ? 'selected' : '' }}>Active</option>
                                    <option value="0" {{ ( $product->status == 0) ? 'selected' : '' }}>Passive</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="category_id">Category</label>
                                <select name="category_id" id="category_id" class="form-control">
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}" {{ ( $category->id == $product->category_id) ? 'selected' : '' }}>{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="brand_id">Brand</label>
                                <select name="brand_id" id="brand_id" class="form-control">
                                    @foreach($brands as $brand)
                                        <option value="{{$brand->id}}" {{ ( $brand->id == $product->brand_id) ? 'selected' : '' }}>{{$brand->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection